name: scope

channels:
  - pytorch
  - nvidia
  - pytorch3d
  - conda-forge
  - aihabitat
  - defaults

dependencies:
  - python=3.9.21
  - pip
  - pytorch=2.4.1
  - torchvision=0.19.1
  - torchaudio=2.4.1
  - pytorch-cuda=11.8
  - habitat-sim=0.2.5
  - headless=2.0
  - faiss-cpu=1.7.4
  - pytorch3d=0.7.8=py39_cu118_pyt241
  - pip:
      - numpy==1.23.5
      - omegaconf==2.3.0
      - open-clip-torch==2.26.1
      - ultralytics==8.2.31
      - supervision==0.21.0
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.10.*
      - scikit-learn==1.4
      - scikit-image==0.22
      - open3d==0.18.0
      - hipart==1.0.4
      - openai==1.35.3
      - httpx==0.27.2
